export { default as Header } from './Header/Header';
export { default as NavBar } from './NavBar/NavBar';
export { default as Slideshow } from './Slideshow/Slideshow';
export { default as About } from './About/About';
export { default as Packages } from './Packages/Packages';
export { default as Featured } from './Featured/Featured';
export { default as SlideshowTwo } from './SlideshowTwo/SlideshowTwo';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer'; 